inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 2.5

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Minitest/MultipleAssertions:
  Max: 4

Lint/RaiseException:
  Enabled: true
